#+options: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Algebraische Zahlentheorie
#+author: Andreas Kellers
#+email: andreas.kellers@gmail.com
#+language: de
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.5.5)
#+cite_export:

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra: \usepackage{ngerman, a4wide}
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+date: \today

* Vorbemerkung

Die nachfolgenden Abschnitte basieren auf dem Buch "Algebraic Number
Theory" von J. S. Milne. Diese Übertragungen in das Deutsche basieren
auf der Version 3.08 vom 19. Juli 2020. Das englische Original ---
neben weiteren Texten und Notizen --- findet sich hier:
https://www.jmilne.org/math/CourseNotes/.

Dank gebührt damit immer dem Autor; etwaige Fehler, Ungenauigkeiten
und Ungelenkheiten gehen einzig auf das Konto des laienhaften
Übersetzers.

Andreas Kellers, November 2022

* Bibliografische Information

Ein algebraischer Zahlkörper ist eine endliche Erweiterung von
$\mathbb{Q}$; eine algebraische Zahl ist Element eines algebraischen
Zahlkörpers. Algebraische Zahlentheorie untersucht die Arithmetik
algebraischer Zahlkörper -- den Ring der ganzen Zahlen in dem
Zahlkörper; den Idealen und Einheiten in diesem; das Maß, in dem
eindeutige Faktorisierung standhält; und so weiter.

Eine abelsche Körpererweiterung ist eine Galois-Erweiterung eines
Körpers mit abelscher Galois-Gruppe. Klassenkörpertheorie beschreibt
die abelschen Erweiterungen eines Zahlkörpers mit der Arithmetik des
Körpers.

Diese Notizen sind der algebraischen Zahlentheorie gewidmet. Der
Nachfolger beschäftigt sich dann mit der Klassenkörpertheorie.

* Dramatis Personae

- /Fermat/ (1601 - 1665). Postulierte das gleichnamige "Theorem" und
  bewies für $m=4$. Er formulierte auch das Problem, die ganzzahligen
  Lösungen der Gleichung $x^2 - ay^2=1$ für $a \in \mathbb{Z}$ zu
  finden. Im Kern ist das die Frage nach den Einheiten in
  $\mathbb{Z}[\sqrt{a}]$. Brouncker erfand einen Algorithmus hierfür,
  unterließ es aber zu beweisen, dass der Algorithmus immer
  funktioniert.
- /Euler/ (1707 - 1783): Er nutze Analysis zum Studium von Primzahlen
  und entdeckte eine frühe Version des quadratischen
  Reziprozitätsgesetzes.
- /Lagrange/ (1736 - 1813): Er bewies, dass der Algorithmus zur Lösung
  der obigen Gleichung immer zu einer Lösung führt, und dass sich jede
  positive ganze Zahl als Summe von vier Quadratzahlen darstellen
  lässt.
- /Legrendre/ (1752 - 1833): Führte das "Legrendre-Symbol"
  $(\frac{m}{p})$ ein und fand die vollständige Form des quadratischen
  Reziprozitätsgesetzes für ungerade Primzahlen $p$ und $q$:
  \begin{equation*}
    \left(\frac{p}{q}\right) \left(\frac{q}{q}\right) = (-1)^{(p-1)(q-1)/4}
  \end{equation*}
  Er bewies ein Ergebnis, dass folgendes lokal-global Prinzip für
  quadratische Formen $Q(x, y, z)$ in drei Variablen über $\mathbb{Q}$
  impliziert: $Q$ hat ein nicht-triviale Lösung in $\mathbb{Q}$ genau
  dann, wenn es eine Lösung in $\mathbb{R}$ gibt und $Q \equiv 0 \,
  \mathrm{mod} \; p^n$ hat eine nicht-triviale Lösung für alle $p$ und
  $n$.
- /Gauss/ (1777 - 1855): Fand den ersten Beweis des quadratischen
  Reziprozitätsgesetzes. Er untersuchte die Gaussschen Zahlen
  $\mathbb{Z}[i]$, um ein quartisches Reziprozitätsgesetz zu
  finden. Er studierte die Klassifikation binärer quadratischer Formen
  über $\mathbb{Z}$, die eng verbunden ist mit der Frage nach der
  Klassenzahl quadratischer Zahlkörper.
- /Dirichlet/ (1805 - 1859): Führte $L-\mathrm{Reihen}$ ein und bewies mit
  ihnen eine analytische Formel für die Klassenzahl und ein Theorem
  zur Dichte der Primzahlen in arithmetischer Progression. Er bewies
  folgendes "Einheiten-Theorem": Sei $\alpha$ eine Lösung des
  irreduziblen Polynoms $f(x)$ mit ganzzahligen
  Koeffizienten. Angenommen, $f(x)$ hat $r$ reelle und $2s$ komplexe
  Wurzeln. Dann ist $\mathbb{Z}[\alpha]^\times$ eine endlich erzeugte
  Gruppe vom Rang $r+s-1$.
- /Kummer/ (1810 - 1893): Ausgelöst von der Suche nach höheren
  Reziprozitätsgesetzen untersuchte er die grundlegende Arithmetik von
  Kreisteilungskörpern und zeigte, dass die eindeutige Faktorisierung
  durch die Einführung von "Idealen Zahlen" wiederhergestellt werden
  kann. Und er bewies Fermats Theorem für reguläre Primzahlen.
- /Hermite/ (1822 - 1901): Er machte wichtige Zuarbeiten zu
  quadratischen Formen und zeigte, dass die Nullstellen eines Polynoms
  vom Grad 5 mit elliptischen Funktionen ausgedrückt werden können.
- /Eisenstein/ (1823 - 1852): Veröffentlichte als erster die
  vollständigen Beweise für die kubischen und quartischen
  Reziprozitätsgesetze.
- /Kronecker/ (1823 - 1891): Er entwickelte eine Alternative zu
  Dedekinds Idealen. Von ihm stammt eine der schönsten Ideen in der
  Mathematik: Die Erzeugung abelscher Erweiterungen von Zahlkörpern
  (/Kroneckers liebster Jugendtraum/).
- /Riemann/ (1826 - 1866): Untersuchte die Riemansche Zeta-Funktion
  und stellte die Riemannsche Vermutung auf.
- /Dedekind/ (1831 - 1916). Legte die moderne Grundlagen der
  algebraischen Zahlentheorie durch eine korrekte Definition des Rings
  der ganzen Zahlen in einem Zahlkörper. Er bewies, dass sich Ideale
  eindeutig in Primideale zerlegen und diese, modulo
  Prinzipal-Idealen, in endliche viele Klassen fallen. Und definierte
  die Zeta-Funktion eines Zahlkörpers.
- /Weber/ (1842 - 1913): Ihm gelangen wichtige Fortschritte in der
  Klassenkörpertheorie und "Kroneckers Jugendtraum".
- /Hensel/ (1861 - 1941): Definierte als erster $p$-adische Zahlkörper
  (als Menge der unendlichen Summen $\sum_{n=-k}^\infty a_n p^n, a_n
  \in \{0, 1, \dots, p-1\}$).
- /Hilbert/ (1862 - 1943): Er verfasste in 1897 eine einflussreiche
  erste Gesamtdarstellung über die algebraische Zahlentheorie. Einige
  seiner berühmten Probleme zielten auf die Zahlentheorie und waren
  ebenso einflussreich.
- /Takagi/ (1875 - 1960): Bewies das Fundamentaltheorem der abelschen
  Klassenkörpertheorie, wie durch Weber und Hilbert vermutet.
- /Noether/ (1882 - 1935): Legte zusammen mit Artin die Grundlagen
  moderner Algebra, die Axiome und eine konzeptionelle Argumentation
  betont. Sie trug bei zur Klassifikation zentraler, einfacher
  Algebren über Zahlkörper.
- /Hecke/ (1887 - 1947): Führte Hecke $L$-Serien als Generalisierung
  von Dirichlets $L$-Serien und Dedekinds Zeta-Funktion ein.
