# -*- fill-column: 100 -*-

#+options: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Algebraische Zahlentheorie
#+author: Andreas Kellers
#+email: andreas.kellers@gmail.com
#+language: de
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.5.5)
#+cite_export:

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra: \usepackage{ngerman, a4wide}
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+date: \today

* Vorbemerkung

  Die nachfolgenden Abschnitte basieren auf dem Buch "Algebraic Number Theory"
  von J. S. Milne. Diese Übertragungen in das Deutsche basieren auf der Version 3.08
  vom 19. Juli 2020. Das englische Original --- neben weiteren Texten und Notizen --- findet sich
  hier: https://www.jmilne.org/math/CourseNotes/.

  Dank gebührt damit immer dem Autor; etwaige Fehler, Ungenauigkeiten und Ungelenkheiten gehen
  einzig und allein auf das Konto des laienhaften Übersetzers.

  Andreas Kellers, November 2022 -- Mai 2023

** TODO Glossar der englischen Fachtermini
   Hier ein kleines Glossar der zentralen englischen Fachbegriffe und ihren Übersetzungen:

   - prime (number) :: Prim oder Primzahl
   - unit :: Einheit (eines Rings)
   - integral domain :: Integritätsring; ein nullteilerfreier kommutativer Ring mit Einselement
   - principal ideal :: Hauptideal; von einem einzigen Element erzeugtes Ideal 
   - principal ideal domain :: Hautpidealring; ein Integritätsring, in dem jedes Ideal ein
     Hauptideal ist
   - associate :: assoziiertes Element; assoziierte Elemente unterscheiden sich nur um den Faktor
     einer Einheit.
   - algebraic integer :: Algebraisch ganze Zahl; Lösung eines monischen Polynoms mit ganzzahligen
     Koeffizienten aus $\mathbb{Z}$.
   - irreducible :: irreduzibel; d.h. keine Einheit und nicht zerlegbar in ein Produkt irreduzibler
     Elemente
   - unique factorization domain (UFD) :: Faktorieller Ring (oder auch Gaußscher Ring oder ZPE-Ring)
     ist ein Integritätsring mit eindeutiger Zerlegung in irreduzible Faktoren für Elemente
     ungleich 0.

* Bibliografische Information

  Ein algebraischer Zahlkörper ist eine endliche Erweiterung von $\mathbb{Q}$; eine algebraische
  Zahl ist Element eines algebraischen Zahlkörpers. Algebraische Zahlentheorie untersucht die
  Arithmetik algebraischer Zahlkörper -- den Ring der ganzen Zahlen in dem Zahlkörper; den Idealen
  und Einheiten in diesem; das Maß, in dem eindeutige Faktorisierung standhält; und so weiter.

  Eine abelsche Körpererweiterung ist eine Galois-Erweiterung eines Körpers mit abelscher
  Galois-Gruppe. Klassenkörpertheorie beschreibt die abelschen Erweiterungen eines Zahlkörpers mit
  der Arithmetik des Körpers.

  Diese Notizen sind der algebraischen Zahlentheorie gewidmet. Der Nachfolger beschäftigt sich dann
  mit der Klassenkörpertheorie.

* Dramatis Personae

  - /Fermat/ (1601 - 1665). Postulierte das gleichnamige "Theorem" und bewies es für $m=4$. Er
    formulierte auch das Problem, die ganzzahligen Lösungen der Gleichung $x^2 - ay^2=1$ für $a \in
    \mathbb{Z}$ zu finden. Im Kern ist das die Frage nach den Einheiten in
    $\mathbb{Z}[\sqrt{a}]$. Brouncker erfand einen Algorithmus hierfür, unterließ es aber zu
    beweisen, dass der Algorithmus immer funktioniert.
  - /Euler/ (1707 - 1783): Er nutze Analysis zum Studium von Primzahlen und entdeckte eine frühe
    Version des quadratischen Reziprozitätsgesetzes.
  - /Lagrange/ (1736 - 1813): Er bewies, dass der Algorithmus zur Lösung der obigen Gleichung immer
    zu einer Lösung führt, und dass sich jede positive ganze Zahl als Summe von vier Quadratzahlen
    darstellen lässt.
  - /Legrendre/ (1752 - 1833): Führte das "Legrendre-Symbol" $(\frac{m}{p})$ ein und fand die
    vollständige Form des quadratischen Reziprozitätsgesetzes für ungerade Primzahlen $p$ und $q$:
    \begin{equation*}
      \left(\frac{p}{q}\right) \left(\frac{q}{q}\right) = (-1)^{(p-1)(q-1)/4}
    \end{equation*}
    Er bewies ein Ergebnis, dass folgendes lokal-global Prinzip für quadratische Formen $Q(x, y, z)$
    in drei Variablen über $\mathbb{Q}$ impliziert: $Q$ hat ein nicht-triviale Lösung in
    $\mathbb{Q}$ genau dann, wenn es eine Lösung in $\mathbb{R}$ gibt und $Q \equiv 0 \pmod{ p^n}$
    hat eine nicht-triviale Lösung für alle $p$ und $n$.
  - /Gauss/ (1777 - 1855): Fand den ersten Beweis des quadratischen Reziprozitätsgesetzes. Er
    untersuchte die Gaussschen Zahlen $\mathbb{Z}[i]$, um ein quartisches Reziprozitätsgesetz zu
    finden. Er studierte die Klassifikation binärer quadratischer Formen über $\mathbb{Z}$, die eng
    verbunden ist mit der Frage nach der Klassenzahl quadratischer Zahlkörper.
  - /Dirichlet/ (1805 - 1859): Führte $L\text{-Reihen}$ ein und bewies mit ihnen eine analytische
    Formel für die Klassenzahl und ein Theorem zur Dichte der Primzahlen in arithmetischer
    Progression. Er bewies folgendes "Einheiten-Theorem": Sei $\alpha$ eine Lösung des irreduziblen
    Polynoms $f(x)$ mit ganzzahligen Koeffizienten. Angenommen, $f(x)$ hat $r$ reelle und $2s$
    komplexe Wurzeln. Dann ist $\mathbb{Z}[\alpha]^\times$ eine endlich erzeugte Gruppe vom Rang
    $r+s-1$.
  - /Kummer/ (1810 - 1893): Ausgelöst von der Suche nach höheren Reziprozitätsgesetzen untersuchte
    er die grundlegende Arithmetik von Kreisteilungskörpern und zeigte, dass die eindeutige
    Faktorisierung durch die Einführung von "Idealen Zahlen" wiederhergestellt werden kann. Und er
    bewies Fermats Theorem für reguläre Primzahlen.
  - /Hermite/ (1822 - 1901): Er machte wichtige Zuarbeiten zu quadratischen Formen und zeigte, dass
    die Nullstellen eines Polynoms vom Grad 5 mit elliptischen Funktionen ausgedrückt werden können.
  - /Eisenstein/ (1823 - 1852): Veröffentlichte als erster die vollständigen Beweise für die
    kubischen und quartischen Reziprozitätsgesetze.
  - /Kronecker/ (1823 - 1891): Er entwickelte eine Alternative zu Dedekinds Idealen. Von ihm stammt
    eine der schönsten Ideen in der Mathematik: Die Erzeugung abelscher Erweiterungen von
    Zahlkörpern (/Kroneckers liebster Jugendtraum/).
  - /Riemann/ (1826 - 1866): Untersuchte die Riemannsche Zeta-Funktion und stellte die Riemannsche
    Vermutung auf.
  - /Dedekind/ (1831 - 1916). Legte die modernen Grundlagen der algebraischen Zahlentheorie durch
    eine korrekte Definition des Rings der ganzen Zahlen in einem Zahlkörper. Er bewies, dass sich
    Ideale eindeutig in Primideale zerlegen und diese, modulo Prinzipal-Idealen, in endliche viele
    Klassen fallen. Und definierte die Zeta-Funktion eines Zahlkörpers.
  - /Weber/ (1842 - 1913): Ihm gelangen wichtige Fortschritte in der Klassenkörpertheorie und
    "Kroneckers Jugendtraum".
  - /Hensel/ (1861 - 1941): Definierte als erster $p\text{-adische}$ Zahlkörper (als Menge der
    unendlichen Summen $\sum_{n=-k}^\infty a_n p^n, a_n \in \{0, 1, \dots, p-1\}$).
  - /Hilbert/ (1862 - 1943): Er verfasste in 1897 eine einflussreiche erste Gesamtdarstellung über
    die algebraische Zahlentheorie. Einige seiner berühmten Probleme zielten auf die Zahlentheorie
    und waren ebenso einflussreich.
  - /Takagi/ (1875 - 1960): Bewies das Fundamentaltheorem der abelschen Klassenkörpertheorie, wie
    durch Weber und Hilbert vermutet.
  - /Noether/ (1882 - 1935): Legte zusammen mit Artin die Grundlagen moderner Algebra, die Axiome
    und eine konzeptionelle Argumentation betont. Sie trug bei zur Klassifikation zentraler,
    einfacher Algebren über Zahlkörper.
  - /Hecke/ (1887 - 1947): Führte Hecke $L\text{-Serien}$ als Generalisierung von Dirichlets
    $L\text{-Serien}$ und Dedekinds Zeta-Funktion ein.
  - /Artin/ (1898 - 1947): Fand das "Artinsche Reziprozitätsgesetz" (als Verbesserung der Ergebnisse
    von Takagi), das zentrale Theorem der Klassenkörpertheorie und führte die Artinschen
    $L\text{-Reihen}$ ein.
  - /Hasse/ (1898 - 1979): Legte den ersten Beweis der lokalen Klassenkörpertheorie vor, bewies das
    Lokal-Global-Prinzip von Hasse und lieferte Beiträge zur Klassifikation der zentralen, einfachen
    Algebren über Zahlkörpern.
  - /Brauer/ (1901 - 1977): Definierte die Brauer-Gruppe und war beteiligt an der Klassifikation
    zentraler einfacher Algebren über Zahlkörpern.
  - /Weil/ (1906 - 1998): Definierte die Weil-Gruppe, die eine Vereinheitlichung von Artinschen und
    Heckeschen $L\mathrm{-Reihen}$ ermöglichte.
  - /Chevalley/ (1909 - 1984): Die Hauptaussagen der Klassenkörpertheorie sind rein algebraisch,
    alle bisherigen Beweise verwendeten die Analysis. Von Chevalley stammt der erste rein
    algebraische Beweis. Seine Einführung von Idèlen erlaubte eine natürliche Formulierung der
    Klassenkörpertheorie für abelsche Erweiterungen.
  - /Iwasawa/ (1917 - 1998): Initiierte einen wichtigen neuen Ansatz in der algebraischen
    Zahlentheorie auf Basis der Theorie von Kurven über endlichen Körpern.
  - /Tate/ (1925 - 2019): Bewies neue Ergebnisse in der Gruppen-Kohomologie, die eine elegante
    Neuformulierung der Klassenkörpertheorie erlaubten. Mit Lubin fand er einen expliziten Weg zur
    Generierung abelscher Erweiterungen lokaler Körper.
  - Langlands (1936 - ): Das Langslands-Programm ist eine breite Palette an Vermutungen, unter
    anderem eine nicht-abelsche Klassenkörpertheorie.

* Einführung

  #+BEGIN_QUOTE
  Es ist sehr zu beklagen, dass die Tugend [der rationalen Zahlen], in Primzahlen zerlegbar zu sein,
  und immer in die gleichen für eine gegebene Zahl, den ganzen Zahlen in Kreisteilungskörpern nicht
  zu eigen ist. -- Kummer 1844 (übersetzt von André Weil).
  #+END_QUOTE

  Das /*Fundamentaltheorem der Arithmetik*/ besagt, dass jede ganze Zahl ungleich 0 geschrieben
  werden kann als
  \begin{equation*}
    m = \pm p_1 \cdots p_n, \quad p_i \enspace \text{Primzahlen,}
  \end{equation*}
  und dass diese Faktorisierung grundsätzlich eindeutig ist.

  Betrachten wir allgemeiner einen Integritätsring $A$. Ein Element $a \in A$ ist eine /*Einheit*/,
  wenn es in $A$ ein Inverses hat (ein Element $b \in A$ mit $ab = 1 = ba$). Die multiplikative
  Gruppe der Einheiten bezeichnen wir mit $A^\times$. Ein Element $\pi$ aus $A$ wird /*prim*/
  genannt, wenn es weder die 0 ist, noch eine Einheit und wenn gilt:
  \begin{equation*}
    \pi | ab \Rightarrow \pi | a \enspace \text{oder} \enspace \pi | b.
  \end{equation*}

  Ist $A$ ein Hauptidealring, kann jedes Element $a$ von $A$ ungleich 0 geschrieben werden als
  \begin{equation*}
    a = u \pi_1 \cdots \pi_{n}, \quad u \enspace \text{Einheit und}
	\enspace \pi_{i} \enspace \text{Primelementen}
  \end{equation*}
  und diese Faktorisierung ist eindeutig bis auf die Reihenfolge und den Austausch von jedem $\pi_i$
  durch ein Produkt mit einer Einheit.

  Eine erste Frage lautet nun, inwieweit diese Eindeutigkeit der Primfaktorzerlegung in Zahlkörpern
  Bestand hat oder nicht mehr gilt. Diese Frage geht einher mit drei Problemen: Erstens ergibt
  Faktorisierung in einem Körper nur Sinn unter Bezugnahme auf einen Unterring. Wir benötigen also
  einen "Ring der ganzen Zahlen" $\mathcal{O}_K$ in dem Zahlkörper $K$. Zweitens, da eine eindeutige
  Faktorisierung im allgemeinen nicht gilt, benötigen wir einen Weg, um zu messen, wie weit die
  eindeutige Faktorisierung nicht mehr gilt. Und drittens benötigen wir, da Faktorisierung nur
  eindeutig bis auf Einheiten definiert ist, ein Verständnis über die Struktur der Gruppe der
  Einheiten $U_K$ in $\mathcal{O}_K$.

** Der Ring der ganzen Zahlen

   Sei $K$ ein algebraischer Zahlkörper. Jedes Element $\alpha$ von $K$ erfüllt eine Gleichung
   \begin{equation*}
     \alpha^{n} + a_{1}\alpha^{n-1} + \cdots + a_{n} = 0
   \end{equation*}
   mit Koeffizienten $a_1, \ldots, a_n$ in $\mathbb{Q}$. $\alpha$ ist eine /*algebraische ganze
   Zahl*/, wenn es eine solche Gleichung mit Koeffizienten $a_1, \ldots, a_n$ in $\mathbb{Z}$
   erfüllt. Wir werden sehen, dass die algebraischen ganzen Zahlen einen Unterring $\mathcal{O}_K$
   von $K$ bilden.

   Eine algebraische Zahl ist genau dann eine ganze Zahl, wenn ihr Minimalpolynom über $\mathbb{Q}$
   Kooeffizienten in $\mathbb{Z}$ hat. Man betrachte z.B. den Körper $K = \mathbb{Q}[\sqrt{d}]$ mit
   einer ganzen, quadratfreien Zahl $d$. Das Minimalpolynom von $\alpha = a + b\sqrt{d}$ mit $b \neq
   0$, $a, b \in \mathbb{Q}$ ist
   \begin{equation*}
     (X - (a + b\sqrt{d})) (X - (a - b\sqrt{d}))
	= X^{2} - 2aX + (a^{2} - b^{2}d),
   \end{equation*}
   also ist $\alpha$ genau dann eine algebraische ganze Zahl, wenn
   \begin{equation*}
     2a \in \mathbb{Z} \quad \text{und} \quad a^{2}-b^{2}d \in \mathbb{Z}.
   \end{equation*}
   Hieraus folgt für den Fall $d = 2,3 \pmod 4$, dass $\alpha$ eine algebraische ganze Zahl ist,
   wenn $a$ und $b$ ganze Zahlen sind, d.h.:
   \begin{equation*}
     \mathcal{O}_{K} = \mathbb{Z}[\sqrt{d}]
       = \left\{a + b\sqrt{d} \quad \text{mit} \quad a,b \in \mathbb{Z}\right\}.
   \end{equation*}
   Im verbleibenden Fall $d = 1 \pmod 4$ ist $\alpha$ eine algebraische ganze Zahl genau dann, wenn
   $a$ und $b$ beides ganze Zahlen oder beide halbe Zahlen sind, d.h.:
   \begin{equation*}
     \mathcal{O}_{K} = \mathbb{Z}[\frac{1+\sqrt{d}}{2}]
       = \left\{a + b\frac{1+\sqrt{d}}{2} \quad \text{mit} \quad a,b \in \mathbb{Z}\right\}.
   \end{equation*}
   Zum Beispiel ist $\mathcal{O}_{\mathbb{Q}[\sqrt{-5}]} = \mathbb{Z}[\sqrt{-5}]$ und
   $\mathcal{O}_{\mathbb{Q}[\sqrt{5}]} = \mathbb{Z}[(1+\sqrt{5})/2]$. Man beachte, dass $(1 +
   \sqrt{5})/2$ der Gleichung $X^2 - X - 1$ genügt, also eine algebraische ganze Zahl in
   $\mathbb{Q}[\sqrt{5}]$ ist.

   Sei $\zeta_d$ eine primitive $d\mathrm{te}$ Einheitswurzel, z.B. $\zeta_d = \exp(2\pi i/d)$ und
   $K = \mathbb{Q}[\zeta_d]$. Wie zu hoffen, werden wir sehen, dass
   \begin{equation*}
     \mathcal{O}_K = \mathbb{Z}[\zeta_d]
       = \left\{ \sum m_i \zeta_d^i \quad \text{mit} \quad m_i \in \mathbb{Z} \right\}
   \end{equation*}

** Faktorisierung

   Ein Element $\pi$ eines Integritätsrings $A$ wird als /*irreduzibel*/ bezeichnet, wenn es keine
   Einheit ist und nicht dargestellt werden kann als Produkt zweier Nicht-Einheiten. Ein Primelement
   ist (offensichtlich) irreduzibel. Ein Ring $A$ ist ein /*faktorieller Ring*/, wenn jedes Element
   ungleich 0 dargestellt werden kann als im wesentlichen eindeutiges Produkt irreduzibler
   Elemente. Ist der Ring der ganzen Zahlen $\mathcal{O}_K$ ein faktorieller Ring? Nein, nicht im
   allgemeinen!

   Wir werden sehen, dass zwar jedes Element von $\mathcal{O}_K$ als Produkt irreduzibler Elemente
   geschrieben werden kann (dies gilt für alle Noetherscheren Ringe), aber die Eindeutigkeit nicht
   immer gegeben ist. In $\mathbb{Z}[\sqrt{-5}]$ gilt zum Beispiel:
   \begin{equation*}
     6 = 2 \cdot 3 = (1 + \sqrt{-5}) (1 - \sqrt{-5}).
   \end{equation*}
   Dass sowohl $2, 3, 1 + \sqrt{-5}$ und $1 - \sqrt{-5}$ irreduzibel sind, erkannt man durch
   Anwendung der Norm-Abbildung:
   \begin{equation*}
     \mathrm{Nm}: \mathbb{Q}[\sqrt{-5}] \rightarrow \mathbb{Q}, \quad
       a + b \sqrt{-5} \mapsto a^2 + 5 b^2.
   \end{equation*}
   Die Abbildung ist multiplikativ und man erkennt einfach, dass für $\alpha \in \mathcal{O}_K$
   gilt:
   \begin{equation*}
     \mathrm{Nm}(\alpha) = 1 \Leftrightarrow \alpha \bar{\alpha}
       \Leftrightarrow \alpha \enspace \text{ist eine Einheit}.
   \end{equation*}
   Angenommen, $1 + \sqrt{-5} = \alpha \beta$, dann ist $\mathrm{Nm}(\alpha \beta) = \mathrm{Nm}(1 +
   \sqrt{-5}) = 6$. Somit muss $\mathrm{Nm}(\alpha) = 1, 2, 3$ oder $6$ sein. Im ersten Fall wäre
   $\alpha$ eine Einheit. Die Fälle 2 und 3 treten nicht auf. Und im letzten Fall ist $\beta$ eine
   Einheit. Die Definition der Norm-Funktion impliziert, dass assoizierte Elemente die gleiche Norm
   haben. Daher bleibt noch zu zeigen, dass $1 + \sqrt{-5}$ und $1 - \sqrt{-5}$ nicht assoziiert
   sind, aber:
   \begin{equation*}
     1 + \sqrt{-5} = (a + b\sqrt{-5}) (1 - \sqrt{-5})
   \end{equation*}
   hat keine Lösung mit $a, b \in \mathbb{Z}$.

   Warum schlägt die eindeutige Faktorisierung in $\mathcal{O}_K$ fehl? Das Problem ist, dass
   irreduzible Elemente in $\mathcal{O}_K$ nicht mehr prim sein müssen. In dem obigen Beispiel ist
   $1 + \sqrt{-5}$ ein Teiler von $2 \cdot 3$, aber weder ein Teiler von 2, noch
   von 3. Faktorisierung in einem Integritätsring (in dem diese existiert, z.B. einem Noetherschen
   Ring) ist nur dann eindeutig, wenn alle irreduziblen Elemente auch prim sind.

   Was lässt sich dennoch erreichen? Man betrachte $210 = 6 \cdot 35 = 10 \cdot 21$. Naiv könnte man
   folgern, dass Faktorisierung in $\mathbb{Z}$ nicht eindeutig ist. Stattdessen ist an der darunter
   liegenden Faktorisierung $210 = (2 \cdot 3)(5 \cdot 7) = (2 \cdot 5)(3 \cdot 7)$ zu erkennen,
   dass diese sehr wohl eindeutig ist.

   Die Idee von Kummer und Dedekind war, die Menge der Primzahlen derart zu erweitern, die zum
   Beispiel in $\mathbb{Z}[\sqrt{-5}]$ eine eindeutige Faktorisierung erlaubt. Dabei soll
   \begin{equation*}
     6 = (\mathfrak{p}_1^2)(\mathfrak{p}_2 \cdot \mathfrak{p}_3) =
       (\mathfrak{p}_1 \cdot \mathfrak{p}_2)(\mathfrak{p}_1 \cdot \mathfrak{p}_3)
   \end{equation*}
   der obigen Faktorisierung von 6 unterliegen.

   Wie definieren wir "ideale Faktoren"? Offensichtlich sollte ein Ideal charakterisiert sein durch
   die algbraischen ganzen Zahlen, die es teilt. Darüber hinaus sollte für die Teilbarkeit durch ein
   Ideal $\mathfrak{a}$ folgende Regeln gelten:
   \begin{equation*}
     \mathfrak{a}|0 \enspace \text{und} \enspace
     \mathfrak{a}|a, \mathfrak{a}|b \Rightarrow \mathfrak{a}|a \pm b \enspace \text{und} \enspace
     \mathfrak{a}|a \Rightarrow \mathfrak{a}|ab \enspace \text{für alle} \enspace b \in \mathcal{O}_K.
   \end{equation*}
   Wenn dann auch noch gilt
   \begin{equation*}
     \mathfrak{a}|ab \Rightarrow \mathfrak{a}|b \enspace \text{oder} \enspace \mathfrak{a}|b,
   \end{equation*}
   bezeichnen wir $\mathfrak{a}$ als "Primideal-Faktor". Da wir von einem Ideal-Fakor nur die Menge
   der Elemente kennen, die es teilt, können wir diese Menge auch zur eindeutigen Beschreibung
   nutzen. Somit ist $\mathfrak{a}$ eine Menge an Elementen aus $\mathcal{O}_K$, für die gilt:
   \begin{equation*}
     0 \in \mathfrak{a} \enspace \text{und} \enspace
     a \in \mathfrak{a}, b \in \mathfrak{a} \Rightarrow a \pm b \in \mathfrak{a} \enspace \text{und} \enspace
     a \in \mathfrak{a} \Rightarrow ab \in \mathfrak{a} \enspace \text{für alle} \enspace b \in \mathcal{O}_K.
   \end{equation*}
   Und ein solches Ideal ist prim, wennn zusätzlich gilt:
   \begin{equation*}
     ab \in \mathfrak{a} \Rightarrow a \in \mathfrak{a} \enspace \text{oder} \enspace b \in \mathfrak{a}.
   \end{equation*}
   Ein Ideal-Faktor ist somit dass, was wir als /*Ideal*/ bezeichnen, und ein Prim-Ideal-Faktor
   bezeichnen wir als /*Primideal*/.

   Offensichtlich lässt sich das Produkt von zwei Idealen über folgende Relation definieren:
   \begin{equation*}
     \mathfrak{a} \mathfrak{b} | c \Leftrightarrow c = \sum_i a_i b_i \enspace \text{mit} \enspace
     \mathfrak{a} | a_i, \enspace \mathfrak{b} | b_i.
   \end{equation*}
   Anders ausgedrückt:
   \begin{equation*}
     \mathfrak{a} \mathfrak{b} = \left\{ \sum_i a_i b_i |
     a_i \in \mathfrak{a}, \enspace b_i \in \mathfrak{b} \right\}.
   \end{equation*}

   Man erkennt einfach, dass dieses Produkt wieder ein Ideal ist. Mit $\mathfrak{a} = (a_1, \ldots,
   a_m)$ und $\mathfrak{b} = (b_1, \ldots, b_n)$ ist somit
   \begin{equation*}
     \mathfrak{a} \cdot \mathfrak{b} = (a_1 b_1, \ldots, a_i b_j,
     \ldots, a_m b_n).
   \end{equation*}

   Mit diesen Definition gewinnt man eine eindeutige Faktorisierung zurück: Ist $a \ne 0$, dann
   exisiert eine im Kern eindeutige Faktorisierung
   \begin{equation*}
      (a) = \mathfrak{p}_1 \cdots \mathfrak{p}_n \enspace \text{mit Primindealen} \enspace \mathfrak{p}_i.
   \end{equation*}

   Aus dem obigen Beispiel $6 = 2 \cdot 3 = (1 + \sqrt{-5}) (1 - \sqrt{-5})$ wird jetzt
   \begin{equation*}
      (6) = (2, 1 + \sqrt{-5})^2(3, 1 + \sqrt{-5})(3, 1 - \sqrt{-5})
   \end{equation*}
   Es sind also folgende Behauptungen zu beweisen:
   \begin{eqnarray*}
      (2, 1 + \sqrt{-5})^2 & = & (2) \\
      (3, 1 + \sqrt{-5})(3, 1 - \sqrt{-5}) & = & (3) \\
      (2, 1 + \sqrt{-5})(3, 1 + \sqrt{-5}) & = & (1 + \sqrt{-5}) \\
      (2, 1 + \sqrt{-5})(3, 1 - \sqrt{-5}) & = & (1 - \sqrt{-5}) \\
   \end{eqnarray*}
   Zum Beispiel gilt $(2, 1 + \sqrt{-5})(2, 1 + \sqrt{-5}) = (4, 2 + 2 \sqrt{-5}, 6)$. Man beachte
   dabei $6 = 2 + 2 \sqrt{-5} - (1 + \sqrt{-5})^2$. Da jeder Generator durch $2$ teilbar ist, gilt
   \begin{equation*}
     (2, 1 + \sqrt{-5})(2, 1 + \sqrt{-5}) \subset (2).
   \end{equation*}
   Umgekehrt ist
   \begin{equation*}
     2 = 6 - 4 \in (4, 2 + 2 \sqrt{-5}, 6)
   \end{equation*}
   Folglich gilt $(2, 1 + \sqrt{-5})^2 = (2)$. Zudem sind die drei Ideale $(2, 1 + \sqrt{-5})$, $(3,
   1 + \sqrt{-5})$ und $(3, 1 - \sqrt{-5})$ alle Primideale. Man betrachte z.B. die Abbildung
   $\mathbb{Z} \to \mathbb{Z}[\sqrt{-5}]/(3, 1 - \sqrt{-5})$. Die Abbildung ist surjektiv mit Kern
   $(3)$. Also gilt
   \begin{equation*}
     \mathbb{Z}[\sqrt{-5}]/(3, 1 - \sqrt{-5}) \simeq \mathbb{Z}/(3),
   \end{equation*}
   einem Integritätsring.

   Es bleibt die Frage, wie weit dies entfernt ist von einer eindeutigen Faktorisierung? Anders
   formuliert: Um wie viele "ideale" Elemente muss man die "wirklichen" Elementen ergänzen, um
   wieder eine eindeutige Faktorisierung zu erreichen? In einen bestimmten Sinn nur endlich viele:
   Eine endliche Menge $S$ von solchen Idealen ist ausreichend, um jedes Ideal darzustellen als
   $\mathfrak{a} \cdot (a)$ mit $\mathfrak{a} \in S$ und $a \in \mathcal{O}_K$. Und noch besser: Wir
   werden eine Gruppe "gebrochener" Ideale $I$ definieren, in der die gebrochenen Hauptideale $(a),
   a \in K^\times$ eine Untergruppe $P$ mit endlichem Index bilden. Dieser Index $(I:P)$ wird als
   *Klassenzahl* $h_K$ von $K$ bezeichnet. Wir werden zeigen, dass
   \begin{equation*}
     h_K = 1 \Leftrightarrow \mathcal{O}_K \enspace \text{ist Hauptidealring}
      \Leftrightarrow \text{Faktorisierung ist eindeutig in} \enspace \mathcal{O}_K
   \end{equation*}
   Ein Theorem von Carlitz besagt, dass bei $h_K = 2$ die Anzahl der Faktoren einer beliebigen Zahl
   aus $K$ unabhängig von der Faktorisierung ist. Die Klassenzahl von $\mathbb{Q}[\sqrt{-5}]$ ist
   $2$ und die Ideale $(3, 1+\sqrt{-5})$, $(3, 1-\sqrt{-5})$, $(7, 3+\sqrt{-5})$ und $(3,
   1-\sqrt{-5})$ sind in $\mathbb{Z}[\sqrt{-5}]$ prim. Somit stellt jedes das nicht-trivale Elemment
   in $I/P$ dar. Und folglich ist das Produkt von zwei beliebigen von ihnen ein Hauptideal. Damit
   erhalten wir drei unterschiedliche Faktorisierungen von $21$ in $\mathbb{Z}[\sqrt{-5}]$:
   \begin{equation*}
     21 = 3 \cdot 7 = (4+\sqrt{-5}) \cdot (4-\sqrt{-5}) = (1 + 2\sqrt{-5}) \cdot (1 - 2\sqrt{-5}),
   \end{equation*}
   alle der Länge 2.

** Einheiten

   Im Gegensatz zu $\mathbb{Z}$ kann der Ring $\mathcal{O}_K$ unendlich viele Einheiten
   enthalten. Zum Beispiel ist $(1 + \sqrt{2})$ eine Einheit unendlicher Ordnung in
   $\mathbb{Z}[\sqrt{2}]$,
   \begin{equation*}
     (1 + \sqrt{2})(1 - \sqrt{2}) = 1; \enspace (1 + \sqrt{2})^m \neq 1 
       \enspace \text{für} \enspace m \neq 0.
   \end{equation*}
   Tatsächlich ist $\mathbb{Z}[\sqrt{2}]^\times = \{ \pm (1 + \sqrt{2})^m \enspace | \enspace m \in
   \mathbb{Z} \}$ und somit ist 
   \begin{equation*}
     \mathbb{Z}[\sqrt{2}] \approx \{ \pm 1\} \times \{ \text{freie abelsche Gruppe vom Rang 1} \}
   \end{equation*}
   Generell kann gezeigt werden (mittels Einheiten-Theorem), dass die Wurzeln von $1$ in $K$ eine
   endliche Gruppe $\mu(K)$ bilden und dass gilt:
   \begin{equation*}
     \mathcal{O}_K^\times \approx \mu(K) \times \mathbb{Z}^r \enspace \text{als abelsche Gruppe}.
   \end{equation*}
   Und darüber hinaus werden wir auch $r$ bestimmen.

** Anwendungen

   Ein Treiber für die Entwicklung der Algebraischen Zahlentheorie war der Versuch, Fermats letztes
   "Theorem" zu beweisen, dass es für $m \ge 3$ keine ganzzahligen Lösungen $(x, y, z)$ der
   Gleichung
   \begin{equation*}
     X^m + Y^m = Z^m
   \end{equation*}
   mit $x$, $y$ und $z$ ungleich $0$ gibt.
   
   Für $m = 3$ kann die Vermutung per unendlichem Abstieg bewiesen werden: Unter der Annahme einer
   Lösung wqird eine kleinere Lösung konstruiert, was letztendlich zu einem Widerspruch führt. Der
   Beweis nutzt die Faktorisierung $X^3 = Z^3 - X^3 = (Z - X)(Z^2 + XZ + X^2)$. Stolperstein für
   eine Übertragung auf größere $m$ ist, dass dann keine derartige Faktorisierung in Polynome mit
   ganzahligen Koeffizienten von Grad $\leq 2$ existiert. Dies führte zur Betrachtung von
   allgemeineren Faktorisierungen.

   Ein berühmtes Ereignis war der Vortrag des französischen Mathematikers Lamé vor der Pariser
   Akademie, in der er behauptete, Fermats Vermutung mittels folgender Ideen bewiesen zu haben. Es
   sei $p > 2$ eine Primzahl und angenommen, $x^p + y^p = z^p$ habe eine ganzzahlige Lösung mit $x$,
   $y$ und $z$ ungleich $0$. Die Lösung lässt sich umformen zu 
   \begin{equation*}
     x^p = z^p - y^p = \prod(z - \zeta^iy), \enspace 0 \leq i \leq p-1, \enspace \zeta = e^{2 \pi i/p}.
   \end{equation*}

   Hiermit zeigte er, wie man zu einer kleineren Lösung der Gleichung gelangt, folglich ein
   Widerspruch. Liousville hinterfragte direkt einen Schritt in Lamés Beweis, bei dem er annimmt,
   dass jeder Faktor $(z - \zeta^iy)$ eine $p$te Potenz ist, sodass es genügt zu zeigen, dass die
   Faktoren paarweise teilerfremd sind und ihr Produkt eine $p$te Potenz ist. Tatsächlich konnte
   Lamé seine Annahme nicht rechtfertigen: $\mathbb{Z}[\zeta]$ ist nicht immer ein Hauptidealring
   und Fermats Theorem blieb weitere 150 Jahre unbewiesen. Dennoch bewies Kummer Fermats Theorem
   kurz nach Lamés Scheitern für alle regulären Primzahlen mit seinen Erkenntnissen über die
   Artithmetik in $\mathbb{Q}[\zeta]$, d.h. für alle Primzahlen $p$, die die Klassenzahl von
   $\mathbb{Q}[\zeta_p]$ nicht teilen.
   
   Eine weitere Nutzung besteht in der Ermittlung von Galois Gruppen. Der Zerfällungskörper eines
   Polynoms $f \in \mathbb{Q}[X]$ ist eine Galois-Erweiterung von $\mathbb{Q}$. Kurse zur
   Galois-Theorie vermitteln die Ermittlung der Galois-Gruppe nur für Polynome kleinen Grades. Erst
   die Algebraische Zahlentheorie erlaubt die Formulierung eines Algorithmus zur Bestimmung der
   Galois-Gruppe für Polynome beliebigen Grades.

* Vorbereitende Maßnahmen aus der Kommutativen Algebra

  Viele der Resultate für Ringe ganzer Zahlen von Zahlkörpern gelten genereller für kommutative
  Ringe. Daher ist es natürlicher, diese Beweise in diesem allgemeineren Kontext zu beweisen.

** Grundlegende Definitionen 

   Wir betrachten nur kommutative Ringe mit einem identitären Element --- d.h. ein Element 1, so
   dass $1a = a$ für alle $a \in A$ --- und Homomorphismen von Ringen bilden die identitären
   Elemente aufeinander ab.

   Ein Ring $B$ mit einem Homomorphismus von Ringen $A \to B$ wird als *$A\text{-Algebra}$*
   bezeichnet. Die Bezeichnung kommt vor allem bei Unterringen $A$ von $B$ zur Anwendung. Mit
   Elementen $\beta_1, \ldots, \beta_m$ aus $B$ bezeichnet $A[\beta_1, \ldots, \beta_m]$ den
   kleinsten Unterring von $B$, der die Elemente $\beta_i$ enthält. Er umfasst alle Polynome in den
   $\beta_i$ mit Koeffizienten aus $A$, also Elementen der Form
   \begin{equation*}
     \sum a_{i_1 \ldots i_m} \beta_1^{i_1} \ldots \beta_m^{i_m}, \enspace a_{i_1 \ldots i_m} \in A.
   \end{equation*}
   Man bezeichnet $A[\beta_1, \ldots, \beta_m]$ als die $A\text{-Subalgebra}$ von $B$ erzeugt durch
   die $\beta_i$. Wenn $A[\beta_1, \ldots, \beta_m] = B$ gilt, spricht man davon, dass die $\beta_i$
   den Ring $B$ als $A\text{-Algebra}$ erzeugen.

   Mit $(a_1, a_2, \ldots)$ bezeichnen wir für Elemente $a_1, a_2, \ldots$ aus $A$ das kleinste
   Ideal, welches die $a_i$ enthält. Es besteht aus den endlichen Summen $\sum c_i a_i$ mit $c_i \in
   A$ und wird als von den Elementen $a_1, a_2, \ldots$ erzeugtes Ideal bezeichnet. Mit Idealen
   $\mathfrak{a}$ und $\mathfrak{b}$ definieren wir $\mathfrak{a} + \mathfrak{b} = \left\{a + b | a
   \in \mathfrak{a}, b \in \mathfrak{b}\right\}$.

   $\mathfrak{a} + \mathfrak{b}$ ist wiederum ein Ideal in $A$, das kleinste Ideal, welches
   $\mathfrak{a}$ und $\mathfrak{b}$ umfasst. Mit $\mathfrak{a} = (a_1, \ldots a_m)$ und
   $\mathfrak{b} = (b_1, \ldots b_n)$ ist $\mathfrak{a} + \mathfrak{b} = (a_1, \ldots a_m, b_1,
   \ldots b_n)$.

   Mit einem Ideal $\mathfrak{a}$ in $A$ kann man den Quotienten $A/\mathfrak{a}$ bilden. Es sei $f$
   der Homomorphismus $f:A \to A/\mathfrak{a}$ mit $a \mapsto a + \mathfrak{a}$. Dann ist
   $\mathfrak{b} \mapsto f^{-1}(\mathfrak{b})$ eine 1-zu-1 Korrespondenz zwischen den Idealen von
   $A/\mathfrak{a}$ in den Idealn von $A$, die $\mathfrak{a}$ umfassen, und es gilt:
   \begin{equation*}
     A / f^{-1}(\mathfrak{b}) \simeq (A/\mathfrak{a}) / \mathfrak{b}
   \end{equation*}

   Ein Ideal $\mathfrak{a}$ von $A$ ist *prim*, wenn aus $ab \in \mathfrak{a}$ folgt, dass $a \in
   \mathfrak{a}$ oder $b \in \mathfrak{a}$. Und ein Idela ist genau dann ein Primideal, wenn der
   Quotientenring $A/\mathfrak{a}$ ein Integritätsring ist. Und ein Element $\pi$ von $A$ ungleich
   $0$ ist *prim*, wenn das Ideal $(\pi)$ ein Primideal ist; dazu äquivlant ist $\pi | ab
   \Rightarrow \pi|a \enspace \text{oder} \enspace \pi|b$.

   Ein Ideal $\mathfrak{m}$ heißt *maximal*, wenn es maximal unter den echten Idealen von $A$ ist,
   d.h. $\mathfrak{m} \neq A$ und es gibt kein Ideal $\mathfrak{a} \neq A$, das $\mathfrak{m}$
   enthält, aber von $\mathfrak{a}$ verschieden ist. Ein Ideal $\mathfrak{a}$ ist maximal genau
   dann, wenn $A/$\mathfrak{a}$ ein Körper ist. Jedes echte Ideal $\mathfrak{a}$ ist enthalten in
   einem maximalen Ideal. Dies ist offensichtlich, sofern $A$ ein noetherscher Ring ist; ansonster
   erfordert der Beweis Zorns Lemma. Inbesondere gilt: Jede Nicht-Einheit von $A$ ist enthalten in
   einem maximalen Ideal. 

   Dies hat Implikationen: $A$ ist ein euklidischer Ring $\Rightarrow$ $A$ it Hauptidealring
   $\Rightarrow$ $A$ ist faktorieller Ring.

** Ideale in Produkten von Ringen

   Proposition: Man betrachte ein Produkt von Ringen $A \times B$. Sind $\mathfrak{a}$ und
   $\mathfrak{b}$ Ideal in $A$ bzw. $B$, dann ist $\mathfrak{a} \times \mathfrak{b}$ ein Ideal in $A
   \times B$. Und jedes Ideal in $A \times B$ ist dieser Gestalt. Die Primideale in $A \times B$
   haben die Form
   \begin{equation*}
     \mathfrak{p} \times B, \enspace \mathfrak{p} \enspace \text{Primideal in} \enspace A, 
     A \times \mathfrak{p}, \enspace \mathfrak{p} \enspace \text{Primideal in} \enspace B.
   \end{equation*}
   Beweis: Sei $\mathfrak{c}$ ein Ideal in $A \times B$ und $\mathfrak{a} = \left\{a \in A | (a, 0)
   \in \mathfrak{c}\right\}$ und $\mathfrak{b} = \left\{b \in B | (0, b) \in \mathfrak{c}\right\}$.
   Offensichtlich gilt $\mathfrak{a} \times \mathfrak{b} \subset \mathfrak{c}$. Sei umgekehrt $(a, b)
   \in \mathfrak{c}$. Dann ist $(a, 0) = (a, b) \cdot (1, 0) \in \mathfrak{c}$ und $(0, 0) = (a, b)
   \cdot (0, 1) \in \mathfrak{c}$ und folglich $(a, b) \in \mathfrak{a} \times \mathfrak{b}$.
   
   Man erinnere sich, dass ein Ideal $\mathfrak{c} \in C$ ein Primideal ist, wenn $C / \mathfrak{c}$
   ein Integritätsring ist. Die Abbildung $A \times B \to A / \mathfrak{a} \times B / \mathfrak{b},
   \enspace (a, b) \mapsto (a + \mathfrak{a}, b + \mathfrak{b})$ hat den Kern $\mathfrak{a} \times
   \mathfrak{b}$ und induziert somit einen Isomorphismus
   \begin{equation*}
     (A \times B) / (\mathfrak{a} \times \mathfrak{b}) \simeq A / \mathfrak{a} \times B / \mathfrak{b}.
   \end{equation*}
   Das Produkt von Ringen ist nur dann ein Integritätsring, wenn einer der Ringe 0 ist und der
   andere ein Integrätsring.
   
   Anmerkung: Das Lemma lässt sich offensichtlich erweitern auf endliche Produkte von Ringen: Die
   Ideale von $A_1 \times \cdots \times A_m$ sind der Gestalt $\mathfrak{a}_1 \times \cdots \times
   \mathfrak{a}_m$ mit Idealen $\mathfrak{a}_i$ in $A_i$ und $\mathfrak{a}_1 \times \cdots \times
   \mathfrak{a}_m$ ist ein Primideal genau dann, wenn es genau ein $j$ gibt mit $\mathfrak{a}_j$ ist
   Primideal in $A_j$ und $\mathfrak{a}_i = A_i$ für alle $i \neq j$.
   
** Noethersche Ringe

   Ein Ring $A$ ist *noethersch*, wenn jedes Ideal in $A$ endlich erzeugt ist.

   *Proposition 1.3*: Die folgenden Bedingungen für einen Ring $A$ sind äquivalent:

   1) $A$ ist noethersch.
   2) Jede aufsteigende Kette von Idealen $\mathfrak{a}_1 \subset \mathfrak{a}_2 \subset \ldots
      \subset \mathfrak{a}_b \subset \ldots$ iwrd konstant, d.h. für ein bestimmtes $n$ gilt
      $\mathfrak{a}_n = \mathfrak{a}_{n+1} = \ldots$.
   3) Jede nichtleere Menge $S$ von Idealen in $A$ hat ein maximales Element, d.h. es gibt ein Ideal
      in $S$, dass nicht in einem anderen Ideal in $S$ enthalten ist.

   *Beweis*: Von 1) nach 2): $\mathfrak{a} = \bigcup \mathfrak{a}_i$ ist ein Ideal und damit endlich erzeugt. Sei
   $\mathfrak{a} = (a_1, \ldots, a_r)$. Für ein $n$ wird $\mathfrak{a}_n$ alle $a_i$ enthalten, und
   somit gilt $\mathfrak{a}_n = \mathfrak{a}_{n+1} = \ldots = \mathfrak{a}$.

   Von 2) nach 3): Sei $\mathfrak{a}_1 \in S$. Ist $\mathfrak{a}_1$ nicht das maximale Ideal, gibt
   es ein Ideal $\mathfrak{a}_2 \in S$ mit $\mathfrak{a}_1 \subsetneq \mathfrak{a}_2$. Ist
   $\mathfrak{a}_2$ nicht maximal, existiert ein Ideal $\mathfrak{a}_3$ usw. Aus 2) folgt, dass
   dieser Prozess nach endlichen Schritten zu einem maximalen Ideal $\mathfrak{a}_n$ führen wird.

   Von 3) nach 1): Sei $\mathfrak{a}$ ein Ideal $A$ und sei $S$ die Menge der endlich erzeugten
   Ideale in $\mathfrak{a}$. $S$ ist nicht leer, da es das Null-Ideal enthält. Somit gibt es auch
   ein maximales Ideal $\mathfrak{a}\prime = (a_1, \dots, a_r)$. Wäre $\mathfrak{a}\prime \neq
   \mathfrak{a}$, gäbe es ein $a \in \mathfrak{a} \setminus \mathfrak{a}\prime$ und das endlich
   erzeugte Ideal $(a_1, \dots, a_r, a)$ wäre ein Ideal in $\mathfrak{a}$, welches
   $\mathfrak{a}\prime$ enthielte, ein Widerspruch zur Bildung von $\mathfrak{a}\prime$.

   Ein berühmtes Theorem von Hilbert sagt aus, dass $k[X_1, \ldots, X_n]$ noethersch
   ist. Praktisch alle Ringe in der algebraischen Zahlentheorie sind noethersch, aber nicht alle
   Ringe, wie z.B. der Ring $k[X_1, \ldots, X_n, \ldots]$ der Polynome in unendlich
   vielen Variablen.

