#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Algebraische Zahlentheorie
#+author: Andreas Kellers
#+email: andreas.kellers@gmail.com
#+language: de
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.5.5)
#+cite_export:

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+date: \today

* Vorbemerkung

Die nachfolgenden Abschnitte basieren auf dem Buch "Algebraic Number
Theory" von J. S. Milne. Diese Übertragungen in das Deutsche basieren
auf der Version 3.08 vom 19. Juli 2020. Das englische Original ---
neben weiteren Texten und Notizen --- findet sich hier:
https://www.jmilne.org/math/CourseNotes/.

Dank gebührt damit immer dem Autor; etwaige Fehler, Ungenauigkeiten
und Ungelenkheiten gehen einzig auf das Konto des laienhaften
Übersetzers.

Andreas Kellers, November 2022

* Bibliografische Information

Ein algebraischer Zahlkörper ist eine endliche Erweiterung von
$\mathbb{Q}$; eine algebraische Zahl ist Element eines algebraischen
Zahlkörpers. Algebraische Zahlentheorie untersucht die Arithmetik
algebraischer Zahlkörper -- den Ring der ganzen Zahlen in dem
Zahlkörper; den Idealen und Einheiten in diesem; das Maß, in dem
eindeutige Faktorisierung standhält; und so weiter.

Eine abelsche Körpererweiterung ist eine Galois-Erweiterung eines
Körpers mit abelscher Galois-Gruppe. Klassenkörpertheorie beschreibt
die abelschen Erweiterungen eines Zahlkörpers mit der Arithmetik des
Körpers.

Diese Notizen sind der algebraischen Zahlentheorie gewidmet. Der
Nachfolger beschäftigt sich dann mit der Klassenkörpertheorie.

* Dramatis Personae

- /Fermat/ (1601 - 1665). Postulierte das gleichnamige "Theorem" und
  bewies für $m=4$. Er formulierte auch das Problem, die ganzzahligen
  Lösungen der Gleichung $x^2 - ay^2=1$ für $a \in \mathbb{Z}$ zu
  finden. Im Kern ist das die Frage nach den Einheiten in
  $\mathbb{Z}[\sqrt{a}]$. Brouncker erfand einen Algorithmus hierfür,
  unterließ es aber zu beweisen, dass der Algorithmus immer
  funktioniert.
- /Euler/ (1707 - 1783): Er nutze Analysis zum Studium von Primzahlen
  und entdeckte eine frühe Version des quadratischen
  Reziprozitätsgesetzes.
- /Lagrange/ (1736 - 1813): Er bewies, dass der Algorithmus zur Lösung
  der obigen Gleichung immer zu einer Lösung führt, und dass sich jede
  positive ganze Zahl als Summe von vier Quadratzahlen darstellen
  lässt.
- /Legrendre/ (1752 - 1833): Führte das "Legrendre-Symbol"
  $(\frac{m}{p})$ ein und fand die vollständige Form des quadratischen
  Reziprozitätsgesetzes für ungerade Primzahlen $p$ und $q$:
  \begin{equation*}
    \left(\frac{p}{q}\right) \left(\frac{q}{q}\right) = (-1)^{(p-1)(q-1)/4}
  \end{equation*}
  Er bewies ein Ergebnis, dass folgendes lokal-global Prinzip für
  quadratische Formen $Q(x, y, z)$ in drei Variablen über $\mathbb{Q}$
  impliziert: $Q$ hat ein nicht-triviale Lösung in $\mathbb{Q}$ genau
  dann, wenn es eine Lösung in $\mathbb{R}$ gibt und $Q \equiv 0 \,
  \mathrm{mod} \; p^n$ hat eine nicht-triviale Lösung für alle $p$ und
  $n$.
